import type { Category, Game } from "./types";

const categorySeeds: [string, string, string, string][] = [
  ["action", "Экшен", "Action", "Swords"],
  ["racing", "Гонки", "Racing", "Car"],
  ["puzzle", "Головоломки", "Puzzle", "Puzzle"],
  ["sports", "Спорт", "Sports", "Trophy"],
  ["io", ".io игры", ".io Games", "Globe"],
  ["adventure", "Приключения", "Adventure", "Map"],
  ["casual", "Казуальные", "Casual", "Gamepad2"],
  ["two-player", "На двоих", "2 Player", "Users"],
];
export const demoCategories: Category[] = categorySeeds.map(
  ([slug, name_ru, name_en, icon], index) => ({
    id: slug,
    slug,
    name_ru,
    name_en,
    icon,
    sort_order: index,
  }),
);

const covers = [
  "photo-1511512578047-dfb367046420",
  "photo-1493711662062-fa541adb3fc8",
  "photo-1542751371-adc38448a05e",
  "photo-1550745165-9bc0b252726f",
  "photo-1538481199705-c710c4e965fc",
  "photo-1598550476439-6847785fcea6",
  "photo-1511882150382-421056c89033",
  "photo-1593305841991-05c297ba4575",
  "photo-1534423861386-85a16f5d13fd",
  "photo-1560419015-7c427e8ae5ba",
  "photo-1552820728-8b83bb6b773f",
  "photo-1497366754035-f200968a6e72",
];

const seeds = [
  [
    "skyline-drift",
    "Skyline Drift",
    "racing",
    "Держи идеальную траекторию и уходи в управляемый занос на ночных улицах.",
    82,
    1384200,
    true,
  ],
  [
    "steel-front",
    "Steel Front",
    "action",
    "Тактический шутер с короткими динамичными раундами и точной стрельбой.",
    8,
    947300,
    false,
  ],
  [
    "orbit-breaker",
    "Orbit Breaker",
    "io",
    "Захватывай орбиту, собирай энергию и переживи столкновение с другими пилотами.",
    202,
    2751100,
    true,
  ],
  [
    "tile-tactics",
    "Tile Tactics",
    "puzzle",
    "Продумывай цепочки ходов и собирай редкие комбинации на изменчивом поле.",
    42,
    682900,
    false,
  ],
  [
    "street-ace",
    "Street Ace",
    "sports",
    "Быстрый уличный баскетбол: финты, блоки и решающий бросок на сирене.",
    25,
    1887600,
    false,
  ],
  [
    "lost-signal",
    "Lost Signal",
    "adventure",
    "Исследуй заброшенную станцию и восстанови сигнал до наступления бури.",
    168,
    521400,
    true,
  ],
  [
    "tiny-kingdoms",
    "Tiny Kingdoms",
    "casual",
    "Строй уютное королевство, объединяй ресурсы и открывай новые острова.",
    318,
    3428100,
    false,
  ],
  [
    "rooftop-rivals",
    "Rooftop Rivals",
    "two-player",
    "Локальная дуэль на крышах: один экран, два игрока и много неожиданностей.",
    355,
    773200,
    false,
  ],
  [
    "nitro-league",
    "Nitro League",
    "racing",
    "Аркадная лига с ускорениями, трамплинами и дерзкими обгонами.",
    64,
    4532900,
    false,
  ],
  [
    "deep-dive",
    "Deep Dive",
    "adventure",
    "Погружайся глубже, улучшай батискаф и отмечай неизведанные зоны.",
    191,
    411800,
    false,
  ],
  [
    "mech-arena",
    "Mech Arena",
    "action",
    "Собери боевого меха и проверь сборку в компактных аренах.",
    12,
    2206700,
    false,
  ],
  [
    "color-loop",
    "Color Loop",
    "puzzle",
    "Спокойная головоломка о цвете, ритме и красивых непрерывных линиях.",
    276,
    1209500,
    false,
  ],
] as const;

export const demoGames: Game[] = seeds.map(
  ([slug, title, category, description, hue, plays, featured], index) => ({
    id: slug,
    slug,
    title,
    category_id: category,
    category_slug: category,
    embed_url: "https://games.crazygames.com/en_US/space-waves/index.html",
    thumbnail_url: `https://images.unsplash.com/${covers[index]}?auto=format&fit=crop&w=900&q=82`,
    tags: [category, "html5", "online"],
    description,
    controls: ["WASD / стрелки — управление", "Пробел / клик — действие"],
    seo_title: null,
    seo_description: null,
    is_published: true,
    is_featured: featured,
    hue,
    plays,
    likes: 720 + index * 83,
    dislikes: 31 + index * 4,
    created_at: new Date(Date.UTC(2026, 8, 24 - index)).toISOString(),
  }),
);
